package se.adaptiv.romanadd;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Tests addition with roman numerals.
 */
public class RomanAdderTest {

    @ParameterizedTest(name = "{0} + {1} = {2}")
    @CsvSource({
            "I, I, II",
            "I, II, III",
            "I, III, IV",
            "II, III, V",
            "III, III, VI",
            "I, IV, V",
            "IV, I, V",
            "IV, II, VI",
            "IV, III, VII",
            "IV, IV, VIII",
            "V, I, VI",
            "I, V, VI",
            "III, V, VIII",
            "VIII, I, IX",
            "V, IV, IX",
            "IV, V, IX",
            "II, VII, IX",
            "VIII, II, X",
            "V, V, X",
            "II, VIII, X",
            "VIII, IV, XII",
            "VIII, VIII, XVI",
            "IX, I, X",
            "I, IX, X",
            "IX, VIII, XVII",
            "IX, IX, XVIII",
            "X, I, XI",
            "X, V, XV",
            "X, VIII, XVIII",
            "I, X, XI",
            "XVII, I, XVIII",
            "XVIII, I, XIX",
            "I, XVIII, XIX",
            "XIX, I, XX",
            "I, XIX, XX",
            "X, X, XX",
            "XVIII, XVIII, XXXVI",
            "XIX, XIX, XXXVIII",
            "XXXVIII, I, XXXIX",
            "I, XXXVIII, XXXIX",
            "XX, XIX, XXXIX",
            "XXXIX, I, XL",
            "XXXV, V, XL",
            "XXX, X, XL",
            "XXI, XIX, XL",
            "IX, XXXI, XL",
            "I, XXXIX, XL",
            "XL, I, XLI",
            "I, XL, XLI",
            "XL, XL, LXXX",
            "XL, IX, XLIX",
            "XLIX, I, L",
            "XLVIII, II, L",
            "XL, X, L",
            "XXX, XX, L",
            "I, XLIX, L",
            "LXXXVIII, I, LXXXIX",
            "L, XXXIX, LXXXIX",
            "I, LXXXVIII, LXXXIX",
            "LXXXIX, I, XC",
            "XC, I, XCI",
            "I, XC, XCI",
            "XC, XC, CLXXX",
            "XCVIII, I, XCIX",
            "I, XCVIII, XCIX",
            "XCIX, I, C",
            "I, XCIX, C",
            "C, LXVI, CLXVI",
            "CCCXCIX, I, CD",
            "CD, I, CDI",
            "I, CD, CDI",
            "CD, CD, DCCC",
            "CD, LXVI, CDLXVI",
            "CDXCIX, I, D",
            "I, CDXCIX, D",
            "D, I, DI",
            "I, D, DI",
            "D, CCCLXXXVIII, DCCCLXXXVIII",
            "DCCCLXXXVIII, I, DCCCLXXXIX",
            "DCCCLXXXIX, I, DCCCXC",
            "I, DCCCLXXXIX, DCCCXC",
            "DCCCXCIX, I, CM",
            "I, DCCCXCIX, CM",
            "CM, I, CMI",
            "I, CM, CMI",
            "CM, CM, MDCCC",
            "CMXCIX, I, M",
            "D, D, M",
            "I, CMXCIX, M",
            "M, I, MI",
            "I, M, MI",
            "MIX, MIX, MMXVIII",
            "M, DCLXI, MDCLXI",
            "MMMDCCCLXXXVIII, I, MMMDCCCLXXXIX",
            "I, MMMDCCCLXXXVIII, MMMDCCCLXXXIX",
            "MMMDCCCXCIX, I, MMMCM",
            "I, MMMDCCCXCIX, MMMCM",
            "MMMCMXCVIII, I, MMMCMXCIX",
            "I, MMMCMXCVIII, MMMCMXCIX"
    })
    void addingTwoRomanNumerals(String numeral1, String numeral2, String numeralSum) {
        assertEquals(numeralSum, RomanAdder.add(numeral1, numeral2));
    }
}
